name: CI

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

permissions:
  contents: read

jobs:
  rust:
    name: rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check libraries and binaries
        run: cargo check --workspace --lib --bins
      - name: Run library tests
        run: cargo test --workspace --lib
